### PR TITLE
[youtube][ui/ux]: Improve styles for playlist runtime section

### LINKED ISSUE #1: [youtube][ui/ux]: Improve styles for playlist runtime section
## Issue 
- [x] UI/UX Improvement

**Description:**
Enhance the styles for the YouTube Playlist runtime section to make it more visually appealing and modern, while ensuring it blends seamlessly with YouTube's UI.

**Expected Behavior:**
The improved styles should provide a modern and pleasing look to the Playlist Runtime Section, complementing YouTube's design.

**Current Behavior:**
Currently, the Playlist Runtime Section has a somewhat bland and uninspiring look that lacks a modern touch and could benefit from an upgrade.

**Suggestions:**
- Enhance the typography and layout for a cleaner and more organized feel.
- Ensure that the color scheme complements YouTube's overall design while adding a fresh twist.
- Consider user experience and usability to make the section more intuitive.

**Screenshots:**
Playlist Runtime Section

**Additional Context:**
To get started, you can find the youtube.css file [here](https://github.com/enrich-platforms/toppings/blob/main/src/css/youtube.css).

### PR DESCRIPTION
**Pull request by AmitSaha15**
**Description**

This PR enhances the visual appeal of the YouTube Playlist Runtime Section, aligning it more closely with YouTube's UI design.

**Closes: #1**

### CODE REVIEW

**Comment by DarhkVoyd** [comment]
Hi @AmitSaha15,

Thank you for contributing in improving the Toppings project. 

We've reviewed the changes you've made, and we see that they align with the original issue's objective. Your work has definitely improved the appearance of the Playlist Runtime Section, and we're pleased with the progress.

However, for smoother collaboration and to prevent duplication of work, we kindly request that contributors first discuss their intention to work on an issue or feature in the original issue thread. This helps us coordinate efforts effectively and ensures that contributors don't invest time and effort on the same task.

Here are a couple of additional recommendations:

1. Consider making the runtime text slightly larger to make it more prominent without going to extremes.

2. While the white background does look pleasing, we would like to explore YouTube's native glass-like translucent container for the section. Please also provide styles for both light and dark themes of YouTube to ensure a consistent and visually appealing experience in any mode.

**Comment by AmitSaha15** [comment]
Hey, @DarhkVoyd...

I'm a beginner in open source contribution. Thanks for your feedback, definitely keep those in mind from next time onwards. 
Please assign this issue to me. I want to try and implement the changes you suggested.

Thanks again.

**Comment by DarhkVoyd** [comment]
No worries at all! I've assigned the issue to you. If you have any questions or need assistance along the way, please don't hesitate to ask.

**Comment by DarhkVoyd** [comment]
@AmitSaha15 Hey, I am unable to assign you to the original issue because you have not participated there. To be able to assign, you are required to have at least have a comment in the original issue.

**Comment by AmitSaha15** [comment]
@DarhkVoyd really sorry as I wasn't aware about that

**Comment by DarhkVoyd** [comment]
No worries at all! Now, I've assigned the issue to you. If you have any questions or need assistance along the way, please don't hesitate to ask.

**Comment by AmitSaha15** [comment]
Hey @DarhkVoyd , please let me know your thoughts.
image

**Comment by DarhkVoyd** [comment]
@AmitSaha15 Kindly commit your changes so that I can test them locally.

**Comment by AmitSaha15** [comment]
> @AmitSaha15 Kindly commit your changes so that I can test them locally.

Done. Please let me know your feedback.

**Comment by DarhkVoyd** [comment]
@AmitSaha15 Great job! The font size enhancement looks much better and blends seamlessly. I'd like to make a few suggestions to further improve the styles:

1. Consider splitting the CSS into common styling, such as padding and margin, and create separate styles for dark and light themes. This will help make the styles more versatile and adaptable.

2. I noticed that YouTube doesn't typically use borders for these elements, so let's remove the border and perhaps reduce the border radius to maintain a consistent look.

3. While the background color is improved, there's room for even better alignment with YouTube's style. I recommend inspecting YouTube's CSS in both light and dark modes using your browser's developer tools. Take note of the color palette used for buttons, div elements, and other metadata on the playlist page. Then, integrate these colors into the light and dark theme CSS we discussed earlier ([selector]-dark and [selector]-light). This will ensure that our styles are consistently aligned with YouTube's design.

These adjustments should help us achieve a more cohesive and polished look. Keep up the great work!

**Comment by AmitSaha15** [comment]
> @AmitSaha15 Great job! The font size enhancement looks much better and blends seamlessly. I'd like to make a few suggestions to further improve the styles:
> 
> 1. Consider splitting the CSS into common styling, such as padding and margin, and create separate styles for dark and light themes. This will help make the styles more versatile and adaptable.
> 2. I noticed that YouTube doesn't typically use borders for these elements, so let's remove the border and perhaps reduce the border radius to maintain a consistent look.
> 3. While the background color is improved, there's room for even better alignment with YouTube's style. I recommend inspecting YouTube's CSS in both light and dark modes using your browser's developer tools. Take note of the color palette used for buttons, div elements, and other metadata on the playlist page. Then, integrate these colors into the light and dark theme CSS we discussed earlier ([selector]-dark and [selector]-light). This will ensure that our styles are consistently aligned with YouTube's design.
> 
> These adjustments should help us achieve a more cohesive and polished look. Keep up the great work!

Alright.... I will be working on your suggestions.

**Comment by DarhkVoyd** [comment]
Hi @AmitSaha15, just checking in on this pull request. Are you still actively working on it? There's another issue that depends on this, and it has been on hold for a while. If you're unable to continue, I can take it from here. Please let me know. Thanks!

**Comment by AmitSaha15** [comment]
> Hi @AmitSaha15, just checking in on this pull request. Are you still actively working on it? There's another issue that depends on this, and it has been on hold for a while. If you're unable to continue, I can take it from here. Please let me know. Thanks!

Yes yes I'm working on it.
I have been busy due to my exams. 😅
And also do you have discord I have some doubts to clear about your last suggestions. @DarhkVoyd

**Comment by DarhkVoyd** [comment]
Good to know you're still working on it. We're planning to set up a Discord server, and we'll update the docs when it's ready. In the meantime, feel free to ask any questions here instead of quote replies. It keeps things tidy.

**Comment by AmitSaha15** [comment]
@DarhkVoyd so I have removed the border and also reduced the border radius.
The other suggestions were to make CSS for dark and light theme, right??

**Comment by DarhkVoyd** [comment]
@AmitSaha15 Yes, the CSS should be something like:
```css
/* Common styles for #metadata-toppings */
#metadata-toppings {
  font-family: 'Roboto', sans-serif;
  padding: 12px 15px;
  background-color: var(--bg-color, #fff);
  color: var(--text-color, #333);
  /* Add any other common styles */
}

/* Dark theme styles for #metadata-toppings */
#metadata-toppings.dark {
  --bg-color: #333;
  --text-color: #fff;
}

/* Light theme styles for #metadata-toppings */
#metadata-toppings.light {
  --bg-color: #fff;
  --text-color: #333;
}

```

**Comment by AmitSaha15** [comment]
@DarhkVoyd got it. Thanks

**Comment by AmitSaha15** [comment]
@DarhkVoyd I removed the border.

But the light theme and dark theme separation is not needed in my opinion. I am adding screenshots below please check and confirm if it's needed or not. I will add if you say that it is neede.
Screenshot 2023-10-14 022826

Screenshot 2023-10-14 022808

**Comment by AmitSaha15** [comment]
As you can see in the left side there is no difference even in youtube's design @DarhkVoyd

**Comment by DarhkVoyd** [comment]
Thanks @AmitSaha15 for your contribution! I removed the unnecessary commented styles. This should be good to go now.

**Review by DarhkVoyd — COMMENTED** [review]
You are right, there is no need to have separate theme styles here. Also, I have removed the unnecessary commented styles.

**Comment by DarhkVoyd** [comment]
Thanks @AmitSaha15 for your contribution! This should be good to go now.

**Comment by AmitSaha15** [comment]
Happy to contribute. Thanks a lot to you too for helping so much. 😇

**Comment by DarhkVoyd** [comment]
@AmitSaha15 I forgot to mention the project currently uses manual versioning so you need to sync the fork and update the version to 1.0.3 in `manifest.json` in src and `package.json` in root. We appreciate your contribution and we can't wait to see your future involvement in our community.

**Pull request merged**
